name: Docker Image CI

on:
  push:
    branches: [ dev, dev_perm]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mfuon/react-test:$(date +%s)
      
    - name: Docker Push
      run: docker push mfuon/react-test